apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: messages-opr
  labels:
    app: spring_message
spec:
  strategy:
    type: Recreate
  replicas: 3
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: spring-message
        name: messages
        version : opr
    spec:
      containers:
        - image: yonwon01/spring_test:latest
          imagePullPolicy: Always
          name: messages-opr
          ports:
            - containerPort: 8082
