apiVersion: v1
kind: Service
metadata:
  name: messages-service
  labels:
    app: spring_message
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32003
  selector:
    app: spring_message
    tier: messages
