---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  labels:
    app: spring_message
data:
  nginx.conf: |
    worker_processes 1;
    events {
    }
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://messages-service/;
        }
      }
    }
