apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: spring_message
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 32012
  selector:
    app: spring_message
    tier: nginx
